### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ShirinovAdil** [Stackeduary/Enterprise-System-Integration-2022#48]
List of minor todos and fixes needed
* [x] Default page should be the login page with the link to the registration
* [x] FIx alert design (sweetalert)
* [x]  Redirect to login on registration success
* [x]  Check for token on beforeEach route
* [x] When car entry is deleted car doesn't get deleted too
* [x]  Logged in user should be able to see login page again
* [x] Fix post login redirect
* [x] Fix logout button
* [x] Redirect to login after logout (router.replace)
* [x] Dropdown for owner when creating a car
